### PR TITLE
Full Tutorial Branch

### PR DESCRIPTION
**Pull request by ecamellini**
This PR **must not** be merged onto master. It's purpose is just to discuss the tutorial branch, where every commit represents a step.

### CODE REVIEW

**Comment by ecamellini** [comment]
@FrancescoCioria I just miss a Step 8 where I use FlexView in some way. Do you have a suggestion on how to use it in a way that makes some sense here? Just replacing the only `<div>` with a FlexView works but is meaningless for the tutorial

**Comment by giogonzo** [comment]
@ecamellini code looks 💯 up to now. TODOs if I'm not missing something:
- add an initial step (or integrate it into the first steps) using `FlexView`
- rewrite completely the last step in the book (it was about testing now it is about `Panel`)
- update steps on the book (I think mainly links + step 4: should justify `noLoaderLoading` + ?)

**Comment by ecamellini** [comment]
@giogonzo my idea was to add a step 8 about FlexView. Then, as you said, I will just have to update the book accordingly.

**Comment by ecamellini** [comment]
@giogonzo added step 8 with FlexView. Check if it's ok: if yes we are done

**Review by giogonzo — APPROVED** [review]

**Comment by giogonzo** [comment]
Looks 👍 
Closing this as planned

**Pull request closed without merging**
